"""phase5_booking_expiry_idempotency

Revision ID: 1ec4e9b5ffc5
Revises: a3503922220f
Create Date: 2026-08-21 16:33:06.655107

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec4e9b5ffc5'
down_revision = 'a3503922220f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # MySQL can't add a NOT NULL column to an existing table without a default.
    # Add as nullable first, backfill, then alter to NOT NULL.
    op.add_column('bookings', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('idempotency_key', sa.String(length=64), nullable=True))

    # Backfill expires_at for existing rows.
    # Prefer created_at + 15 minutes; if created_at is null (shouldn't happen), use now + 15 minutes.
    op.execute(
        "UPDATE bookings SET expires_at = COALESCE(DATE_ADD(created_at, INTERVAL 15 MINUTE), DATE_ADD(NOW(), INTERVAL 15 MINUTE)) "
        "WHERE expires_at IS NULL"
    )

    op.alter_column('bookings', 'expires_at', existing_type=sa.DateTime(timezone=True), nullable=False)
    op.create_index('ix_bookings_expires_at', 'bookings', ['expires_at'], unique=False)
    op.create_index('ix_bookings_idempotency_key', 'bookings', ['idempotency_key'], unique=False)
    op.create_unique_constraint(op.f('uq_bookings_user_id_idempotency_key'), 'bookings', ['user_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_bookings_user_id_idempotency_key'), 'bookings', type_='unique')
    op.drop_index('ix_bookings_idempotency_key', table_name='bookings')
    op.drop_index('ix_bookings_expires_at', table_name='bookings')
    op.drop_column('bookings', 'idempotency_key')
    op.drop_column('bookings', 'expired_at')
    op.drop_column('bookings', 'expires_at')
    # ### end Alembic commands ###
