"""phase6_8_9_10_staff_membership_reviews_notifications

Revision ID: 5c730bcf3484
Revises: 8b27eaaf4e67
Create Date: 2026-08-21 17:52:16.843189

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c730bcf3484'
down_revision = '8b27eaaf4e67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_events'))
    )
    op.create_index('ix_notification_events_created_at', 'notification_events', ['created_at'], unique=False)
    op.create_index('ix_notification_events_status', 'notification_events', ['status'], unique=False)
    op.create_index('ix_notification_events_type', 'notification_events', ['event_type'], unique=False)
    op.create_index('ix_notification_events_user_id', 'notification_events', ['user_id'], unique=False)
    op.create_table('gym_membership_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_membership_plans_gym_id_gyms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_membership_plans'))
    )
    op.create_index('ix_gym_membership_plans_gym_id', 'gym_membership_plans', ['gym_id'], unique=False)
    op.create_index('ix_gym_membership_plans_is_active', 'gym_membership_plans', ['is_active'], unique=False)
    op.create_table('gym_reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_reviews_gym_id_gyms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_gym_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_reviews')),
    sa.UniqueConstraint('gym_id', 'user_id', name=op.f('uq_gym_reviews_gym_id_user_id'))
    )
    op.create_index('ix_gym_reviews_created_at', 'gym_reviews', ['created_at'], unique=False)
    op.create_index('ix_gym_reviews_gym_id', 'gym_reviews', ['gym_id'], unique=False)
    op.create_index('ix_gym_reviews_status', 'gym_reviews', ['status'], unique=False)
    op.create_index('ix_gym_reviews_user_id', 'gym_reviews', ['user_id'], unique=False)
    op.create_table('gym_staff_assignments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_staff_assignments_gym_id_gyms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_gym_staff_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_staff_assignments')),
    sa.UniqueConstraint('gym_id', 'user_id', name=op.f('uq_gym_staff_assignments_gym_id_user_id'))
    )
    op.create_index('ix_gym_staff_assignments_gym_id', 'gym_staff_assignments', ['gym_id'], unique=False)
    op.create_index('ix_gym_staff_assignments_user_id', 'gym_staff_assignments', ['user_id'], unique=False)
    op.create_table('user_memberships',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_user_memberships_gym_id_gyms')),
    sa.ForeignKeyConstraint(['plan_id'], ['gym_membership_plans.id'], name=op.f('fk_user_memberships_plan_id_gym_membership_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_memberships'))
    )
    op.create_index('ix_user_memberships_gym_id', 'user_memberships', ['gym_id'], unique=False)
    op.create_index('ix_user_memberships_status', 'user_memberships', ['status'], unique=False)
    op.create_index('ix_user_memberships_user_id', 'user_memberships', ['user_id'], unique=False)
    # MySQL-safe: add with default for existing rows
    op.add_column('gyms', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # (Optional) keep server_default in place to avoid MySQL issues when inserting without explicit value
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyms', 'is_featured')
    op.drop_index('ix_user_memberships_user_id', table_name='user_memberships')
    op.drop_index('ix_user_memberships_status', table_name='user_memberships')
    op.drop_index('ix_user_memberships_gym_id', table_name='user_memberships')
    op.drop_table('user_memberships')
    op.drop_index('ix_gym_staff_assignments_user_id', table_name='gym_staff_assignments')
    op.drop_index('ix_gym_staff_assignments_gym_id', table_name='gym_staff_assignments')
    op.drop_table('gym_staff_assignments')
    op.drop_index('ix_gym_reviews_user_id', table_name='gym_reviews')
    op.drop_index('ix_gym_reviews_status', table_name='gym_reviews')
    op.drop_index('ix_gym_reviews_gym_id', table_name='gym_reviews')
    op.drop_index('ix_gym_reviews_created_at', table_name='gym_reviews')
    op.drop_table('gym_reviews')
    op.drop_index('ix_gym_membership_plans_is_active', table_name='gym_membership_plans')
    op.drop_index('ix_gym_membership_plans_gym_id', table_name='gym_membership_plans')
    op.drop_table('gym_membership_plans')
    op.drop_index('ix_notification_events_user_id', table_name='notification_events')
    op.drop_index('ix_notification_events_type', table_name='notification_events')
    op.drop_index('ix_notification_events_status', table_name='notification_events')
    op.drop_index('ix_notification_events_created_at', table_name='notification_events')
    op.drop_table('notification_events')
    # ### end Alembic commands ###
