"""phase3_gym_tables

Revision ID: 5c76497351e4
Revises: ae4876fb0042
Create Date: 2026-08-21 15:20:24.273621

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c76497351e4'
down_revision = 'ae4876fb0042'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_facilities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_facilities')),
    sa.UniqueConstraint('name', name=op.f('uq_gym_facilities_name'))
    )
    op.create_table('gyms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_gyms_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gyms'))
    )
    op.create_index('ix_gyms_city', 'gyms', ['city'], unique=False)
    op.create_index('ix_gyms_is_active', 'gyms', ['is_active'], unique=False)
    op.create_index('ix_gyms_owner_user_id', 'gyms', ['owner_user_id'], unique=False)
    op.create_index('ix_gyms_status', 'gyms', ['status'], unique=False)
    op.create_table('gym_facility_mapping',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('facility_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['gym_facilities.id'], name=op.f('fk_gym_facility_mapping_facility_id_gym_facilities')),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_facility_mapping_gym_id_gyms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_facility_mapping')),
    sa.UniqueConstraint('gym_id', 'facility_id', name=op.f('uq_gym_facility_mapping_gym_id_facility_id'))
    )
    op.create_index('ix_gym_facility_mapping_facility_id', 'gym_facility_mapping', ['facility_id'], unique=False)
    op.create_index('ix_gym_facility_mapping_gym_id', 'gym_facility_mapping', ['gym_id'], unique=False)
    op.create_table('gym_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_images_gym_id_gyms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_images'))
    )
    op.create_index('ix_gym_images_gym_id', 'gym_images', ['gym_id'], unique=False)
    op.create_index('ix_gym_images_is_cover', 'gym_images', ['is_cover'], unique=False)
    op.create_table('gym_operating_hours',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_operating_hours_gym_id_gyms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_operating_hours')),
    sa.UniqueConstraint('gym_id', 'day_of_week', name=op.f('uq_gym_operating_hours_gym_id_day_of_week'))
    )
    op.create_index('ix_gym_operating_hours_gym_id', 'gym_operating_hours', ['gym_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gym_operating_hours_gym_id', table_name='gym_operating_hours')
    op.drop_table('gym_operating_hours')
    op.drop_index('ix_gym_images_is_cover', table_name='gym_images')
    op.drop_index('ix_gym_images_gym_id', table_name='gym_images')
    op.drop_table('gym_images')
    op.drop_index('ix_gym_facility_mapping_gym_id', table_name='gym_facility_mapping')
    op.drop_index('ix_gym_facility_mapping_facility_id', table_name='gym_facility_mapping')
    op.drop_table('gym_facility_mapping')
    op.drop_index('ix_gyms_status', table_name='gyms')
    op.drop_index('ix_gyms_owner_user_id', table_name='gyms')
    op.drop_index('ix_gyms_is_active', table_name='gyms')
    op.drop_index('ix_gyms_city', table_name='gyms')
    op.drop_table('gyms')
    op.drop_table('gym_facilities')
    # ### end Alembic commands ###
