"""phase5_booking_owner_admin_ops

Revision ID: 8b27eaaf4e67
Revises: 1ec4e9b5ffc5
Create Date: 2026-08-21 16:44:59.363226

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b27eaaf4e67'
down_revision = '1ec4e9b5ffc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('attendance_status', sa.String(length=20), nullable=True))
    op.add_column('bookings', sa.Column('attendance_marked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('attendance_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'attendance_note')
    op.drop_column('bookings', 'attendance_marked_at')
    op.drop_column('bookings', 'attendance_status')
    # ### end Alembic commands ###
