"""phase4_gym_status_history

Revision ID: a21b682fa0c5
Revises: 5c76497351e4
Create Date: 2026-08-21 15:57:57.554420

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21b682fa0c5'
down_revision = '5c76497351e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_gym_status_history_changed_by_user_id_users')),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_status_history_gym_id_gyms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_status_history'))
    )
    op.create_index('ix_gym_status_history_created_at', 'gym_status_history', ['created_at'], unique=False)
    op.create_index('ix_gym_status_history_gym_id', 'gym_status_history', ['gym_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gym_status_history_gym_id', table_name='gym_status_history')
    op.drop_index('ix_gym_status_history_created_at', table_name='gym_status_history')
    op.drop_table('gym_status_history')
    # ### end Alembic commands ###
