"""phase5_bookings

Revision ID: a3503922220f
Revises: ee35e81e52c7
Create Date: 2026-08-21 16:26:04.082182

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3503922220f'
down_revision = 'ee35e81e52c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('gym_slot_id', sa.BigInteger(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_bookings_gym_id_gyms')),
    sa.ForeignKeyConstraint(['gym_slot_id'], ['gym_slots.id'], name=op.f('fk_bookings_gym_slot_id_gym_slots')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index('ix_bookings_gym_id', 'bookings', ['gym_id'], unique=False)
    op.create_index('ix_bookings_gym_slot_id', 'bookings', ['gym_slot_id'], unique=False)
    op.create_index('ix_bookings_slot_date', 'bookings', ['slot_date'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_user_id', 'bookings', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_payments_booking_id'))
    )
    op.create_index('ix_payments_booking_id', 'payments', ['booking_id'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_booking_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_bookings_user_id', table_name='bookings')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_slot_date', table_name='bookings')
    op.drop_index('ix_bookings_gym_slot_id', table_name='bookings')
    op.drop_index('ix_bookings_gym_id', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
