"""phase5_slots

Revision ID: ee35e81e52c7
Revises: a21b682fa0c5
Create Date: 2026-08-21 16:04:04.479616

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee35e81e52c7'
down_revision = 'a21b682fa0c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_slots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_slots_gym_id_gyms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_slots'))
    )
    op.create_index('ix_gym_slots_gym_id', 'gym_slots', ['gym_id'], unique=False)
    op.create_index('ix_gym_slots_is_active', 'gym_slots', ['is_active'], unique=False)
    op.create_table('slot_availability',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gym_slot_id', sa.BigInteger(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('capacity_override', sa.Integer(), nullable=True),
    sa.Column('booked_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['gym_slot_id'], ['gym_slots.id'], name=op.f('fk_slot_availability_gym_slot_id_gym_slots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slot_availability')),
    sa.UniqueConstraint('gym_slot_id', 'slot_date', name=op.f('uq_slot_availability_gym_slot_id_slot_date'))
    )
    op.create_index('ix_slot_availability_gym_slot_id', 'slot_availability', ['gym_slot_id'], unique=False)
    op.create_index('ix_slot_availability_slot_date', 'slot_availability', ['slot_date'], unique=False)
    op.create_index('ix_slot_availability_status', 'slot_availability', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slot_availability_status', table_name='slot_availability')
    op.drop_index('ix_slot_availability_slot_date', table_name='slot_availability')
    op.drop_index('ix_slot_availability_gym_slot_id', table_name='slot_availability')
    op.drop_table('slot_availability')
    op.drop_index('ix_gym_slots_is_active', table_name='gym_slots')
    op.drop_index('ix_gym_slots_gym_id', table_name='gym_slots')
    op.drop_table('gym_slots')
    # ### end Alembic commands ###
