import { useState } from 'react'
import { adminApproveGym, adminRejectGym, fetchAdminGyms, fetchAdminUser, type AdminGymListItem } from '../screens/Admin/api'
import { dateLabel, money } from '../services/client'
import { gymService } from './services'
import { useAdminResource, useListQuery } from './hooks'
import { Alert, Button, ConfirmationModal, DataCard, DataTable, Details, FilterPanel, Icon, Identity, ImageGallery, Link, PageHeader, Pagination, Resource, SearchInput, StatusBadge, Tabs, personName } from './UI'

const statuses = [{ value: '', label: 'All gyms' }, { value: 'PENDING_APPROVAL', label: 'Pending approval' }, { value: 'APPROVED', label: 'Approved' }, { value: 'REJECTED', label: 'Rejected' }, { value: 'DRAFT', label: 'Draft' }, { value: 'SUSPENDED', label: 'Suspended' }]
export function GymCard({ gym }: { gym: AdminGymListItem }) { return <><div className="ad-record-top"><Identity name={gym.name} caption={gym.city || 'Location not provided'} icon="gym" /><StatusBadge status={gym.status} /></div><p>Owner #{gym.owner_user_id}</p><small>Created {dateLabel(gym.created_at)}</small><Link className="fg-button fg-button--secondary" to={`/admin/gyms/${gym.id}`}>View gym</Link></> }
export default function Gyms({ id, review }: { id?: number; review?: boolean }) { return id ? <GymDetails id={id} review={review} /> : <GymList /> }
function GymList() {
  const list = useListQuery(); const status = list.query.get('status') || ''; const owner = list.query.get('owner_user_id') || ''
  const resource = useAdminResource(() => fetchAdminGyms({ q: list.query.get('q') || undefined, status: status || undefined, owner_user_id: owner ? Number(owner) : undefined, limit: 21, offset: list.offset }), `gyms:${list.query}`)
  return <><PageHeader title="Gyms" subtitle="Manage and review gyms on FitiGo." /><DataCard><Tabs value={status} onChange={value => list.update({ status: value })} options={statuses} /><div className="ad-list-toolbar"><SearchInput value={list.search} onChange={list.setSearch} placeholder="Search gym name or city…" busy={list.searching} /><FilterPanel reset={() => list.update({ owner_user_id: '', status: '' })}><label className="ad-field"><span>Owner ID</span><input type="number" min="1" step="1" value={owner} placeholder="All owners" onChange={e => list.update({ owner_user_id: e.target.value })} /></label></FilterPanel></div><Resource resource={resource}>{rows => <><DataTable rows={rows.slice(0, 20)} label="Platform gyms" empty="No gyms found." mobile={gym => <GymCard gym={gym} />} columns={[{ label: 'Gym', cell: gym => <Identity icon="gym" name={gym.name} caption={`#${gym.id}`} /> }, { label: 'Owner', cell: gym => <Link to={`/admin/users/${gym.owner_user_id}`} className="ad-text-link">Owner #{gym.owner_user_id}</Link> }, { label: 'Location', cell: gym => gym.city || 'Not provided' }, { label: 'Status', cell: gym => <StatusBadge status={gym.status} /> }, { label: 'Created', cell: gym => dateLabel(gym.created_at) }, { label: 'Actions', cell: gym => <Link className="ad-table-link" to={`/admin/gyms/${gym.id}${gym.status === 'PENDING_APPROVAL' ? '/review' : ''}`}>{gym.status === 'PENDING_APPROVAL' ? 'Review' : 'View'}</Link> }]} /><Pagination page={list.page} count={Math.min(20, rows.length)} hasMore={rows.length > 20} onPage={page => list.update({ page: String(page) })} /></>}</Resource></DataCard></>
}
function OwnerInformation({ id }: { id: number }) {
  const owner = useAdminResource(() => fetchAdminUser(id), `gym-owner:${id}`)
  return <DataCard title="Owner information"><Resource resource={owner}>{user => <><Identity name={personName(user)} caption={user.email} /><Details rows={[["Owner ID", <Link className="ad-text-link" to={`/admin/users/${id}`}>#{id} · View account</Link>], ['Phone', user.phone], ['Account status', <StatusBadge status={user.status} />]]} /></>}</Resource></DataCard>
}
function PublicPreview({ id }: { id: number }) {
  const resource = useAdminResource(() => gymService.publicPreview(id), `gym-preview:${id}`)
  const [tab, setTab] = useState('Overview')
  return <Resource resource={resource}>{gym => <><ImageGallery name={gym.name} images={gym.images.map(image => ({ src: `/uploads/${image.file_path}`, alt: image.original_filename || gym.name }))} /><DataCard><Tabs label="Gym information" value={tab} onChange={setTab} options={['Overview', 'Facilities', 'Pricing', 'Operating hours', 'Location', 'Photos'].map(value => ({ value, label: value }))} /><div className="ad-tab-content">{tab === 'Overview' && <><h2>About {gym.name}</h2><p className="ad-description">{gym.description || 'No description provided.'}</p><Details rows={[["Contact email", gym.email], ['Phone', gym.phone], ['Created', dateLabel(gym.created_at)]]} /></>}{tab === 'Facilities' && <><h2>Facilities</h2>{gym.facilities.length ? <div className="ad-facilities">{gym.facilities.map(facility => <span key={facility.id}><Icon name="check" size={17} />{facility.name}</span>)}</div> : <p>No facilities provided.</p>}</>}{tab === 'Pricing' && <><h2>Pricing</h2><Details rows={[["Gym access · per person", gym.gym_price_per_person === undefined ? 'Not provided' : money(gym.gym_price_per_person)]]} /></>}{tab === 'Operating hours' && <><h2>Operating hours</h2>{gym.operating_hours.length ? <Details rows={gym.operating_hours.map(hours => [['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][hours.day_of_week], hours.is_closed ? 'Closed' : `${hours.open_time?.slice(0, 5) || 'Not provided'} – ${hours.close_time?.slice(0, 5) || 'Not provided'}`])} /> : <p>No operating hours provided.</p>}</>}{tab === 'Location' && <><h2>Location</h2><p className="ad-description">{[gym.address_line_1, gym.address_line_2, gym.city, gym.state, gym.postal_code, gym.country].filter(Boolean).join(', ') || 'No address provided.'}</p></>}{tab === 'Photos' && <ImageGallery name={gym.name} images={gym.images.map(image => ({ src: `/uploads/${image.file_path}`, alt: image.original_filename || gym.name }))} />}</div></DataCard></>}</Resource>
}
function GymDetails({ id, review }: { id: number; review?: boolean }) {
  const resource = useAdminResource(signal => gymService.summary(id, signal), `gym:${id}`)
  const [action, setAction] = useState<'approve' | 'reject' | null>(null)
  return <><PageHeader title={review ? 'Gym approval review' : 'Gym details'} subtitle={review ? 'Review the available submission before making a decision.' : 'Partner information and customer-facing preview'} back={{ to: '/admin/gyms', label: 'Back to Gyms' }} /><Resource resource={resource}>{gym => <><div className="ad-record-heading"><Identity icon="gym" name={gym.name} caption={gym.city || 'Location not provided'} /><StatusBadge status={gym.status} /><Button variant="secondary" onClick={resource.retry}>Refresh</Button></div><div className="ad-detail-grid"><DataCard title="Gym information"><Details rows={[["Gym name", gym.name], ['Gym ID', `#${gym.id}`], ['Location', gym.city], ['Created', dateLabel(gym.created_at)], ['Approval status', <StatusBadge status={gym.status} />], ['Enabled', gym.is_active ? 'Yes' : 'No']]} /></DataCard>{gym.owner_user_id && <OwnerInformation id={gym.owner_user_id} />}</div>{gym.status === 'APPROVED' && gym.is_active ? <><Alert tone="success">This approved gym is enabled on FitiGo. The preview below uses the public gym endpoint.</Alert><PublicPreview id={id} /></> : <DataCard title="Submission details"><Alert tone="warning">The current admin API provides summary information only. Photos, description, facilities, pricing and operating hours for non-public gyms are not available to administrators. A complete approval review cannot be performed here yet.</Alert>{gym.status === 'REJECTED' && <p className="ad-description">This gym is rejected. The backend does not expose its saved rejection reason or status history.</p>}</DataCard>}<div className="ad-sticky-actions"><div><strong>Administrative review</strong><small>The server validates each approval or rejection request.</small></div><Button variant="danger" onClick={() => setAction('reject')}>Reject Gym</Button><Button onClick={() => setAction('approve')}><Icon name="check" size={17} />Approve Gym</Button></div>{action && <ConfirmationModal title={action === 'approve' ? 'Approve Gym?' : 'Reject Gym'} confirm={action === 'approve' ? 'Approve Gym' : 'Reject Gym'} danger={action === 'reject'} reason={action === 'reject' ? 'required' : undefined} onClose={() => setAction(null)} action={reason => action === 'approve' ? adminApproveGym(id) : adminRejectGym(id, reason)} success={action === 'approve' ? 'Gym approved successfully.' : 'Gym rejected successfully.'} onSuccess={resource.retry}><p><strong>{gym.name}</strong> · Current status: <StatusBadge status={gym.status} /></p><p>{action === 'approve' ? 'Request approval for this gym. If approved and enabled by the backend, it will be visible to customers.' : 'Please provide a reason for rejection. The backend will validate and store your decision.'}</p>{!(gym.status === 'APPROVED' && gym.is_active) && <Alert tone="warning">Full submission details are unavailable in this portal. Verify the owner’s submission through your established review process before proceeding.</Alert>}</ConfirmationModal>}</>}</Resource></>
}