import { useState } from 'react'
import { adminUpdateUserStatus, fetchAdminUser, fetchAdminUsers, type AdminUserListItem } from '../screens/Admin/api'
import { dateLabel } from '../services/client'
import { useAdminResource, useListQuery } from './hooks'
import { Alert, Button, ConfirmationModal, DataCard, DataTable, Details, FilterPanel, Identity, Link, PageHeader, Pagination, Resource, SearchInput, Select, StatusBadge, Tabs, personName, readable } from './UI'

const roles = [{ value: '', label: 'All users' }, { value: 'CUSTOMER', label: 'Customers' }, { value: 'GYM_OWNER', label: 'Owners' }, { value: 'ADMIN', label: 'Admins' }, { value: 'SUPER_ADMIN', label: 'Super admins' }]
export function UserCard({ user }: { user: AdminUserListItem }) { return <><div className="ad-record-top"><Identity name={personName(user)} caption={user.roles.map(readable).join(', ')} /><StatusBadge status={user.status} /></div><p>{user.email}</p><small>Created {dateLabel(user.created_at)}</small><Link className="fg-button fg-button--secondary" to={`/admin/users/${user.id}`}>View user</Link></> }
export default function Users({ id }: { id?: number }) { return id ? <UserDetails id={id} /> : <UserList /> }
function UserList() {
  const list = useListQuery(); const role = list.query.get('role') || ''; const status = list.query.get('status') || ''
  // Backend applies role filtering after pagination. Preserve its raw 20-record window.
  // A short role-filtered page does NOT mean end-of-list; query the same unfiltered window.
  const resource = useAdminResource(async () => {
    const params = { q: list.query.get('q') || undefined, status: status || undefined, offset: list.offset }
    if (!role) {
      const rows = await fetchAdminUsers({ ...params, limit: 21 })
      return { rows: rows.slice(0, 20), hasMore: rows.length > 20 }
    }
    const [rows, window] = await Promise.all([fetchAdminUsers({ ...params, role: role || undefined, limit: 20 }), fetchAdminUsers({ ...params, limit: 21 })])
    return { rows, hasMore: window.length > 20 }
  }, `users:${list.query}`)
  return <><PageHeader title="Users" subtitle="Manage FitiGo platform users." /><DataCard><Tabs options={roles} value={role} onChange={value => list.update({ role: value })} /><div className="ad-list-toolbar"><SearchInput value={list.search} onChange={list.setSearch} placeholder="Search name, email or phone…" busy={list.searching} /><FilterPanel reset={() => list.update({ status: '', role: '' })}><Select label="Account status" value={status} onChange={value => list.update({ status: value })} options={[{ value: '', label: 'All statuses' }, { value: 'ACTIVE', label: 'Active' }, { value: 'INACTIVE', label: 'Inactive' }]} /></FilterPanel></div><Resource resource={resource}>{data => <><DataTable rows={data.rows} label="Platform users" empty="No users found." mobile={user => <UserCard user={user} />} columns={[{ label: 'User', cell: user => <Identity name={personName(user)} caption={`#${user.id}`} /> }, { label: 'Contact', cell: user => <span className="ad-stacked">{user.email}<small>{user.phone || 'No phone provided'}</small></span> }, { label: 'Role', cell: user => user.roles.map(readable).join(', ') }, { label: 'Status', cell: user => <StatusBadge status={user.status} /> }, { label: 'Created', cell: user => dateLabel(user.created_at) }, { label: 'Actions', cell: user => <Link className="ad-table-link" to={`/admin/users/${user.id}`} label={`View ${personName(user)}`}>View</Link> }]} />{role && <p className="ad-pagination-note">Role filtering applies within each server page. Continue to the next page to see more matching users.</p>}<Pagination page={list.page} count={data.rows.length} hasMore={data.hasMore} onPage={page => list.update({ page: String(page) })} /></>}</Resource></DataCard></>
}
function UserDetails({ id }: { id: number }) {
  const resource = useAdminResource(() => fetchAdminUser(id), `user:${id}`); const [action, setAction] = useState<string | null>(null)
  return <><PageHeader title="User details" subtitle="Account information and platform access" back={{ to: '/admin/users', label: 'Back to Users' }} /><Resource resource={resource}>{user => <><div className="ad-record-heading"><Identity name={personName(user)} caption={user.roles.map(readable).join(' · ')} /><StatusBadge status={user.status} /><Button variant="secondary" onClick={resource.retry}>Refresh</Button></div><div className="ad-detail-grid"><DataCard title="Personal information"><Details rows={[["Name", personName(user)], ['Email', user.email], ['Phone', user.phone]]} /></DataCard><DataCard title="Account information"><Details rows={[["User ID", `#${user.id}`], ['Created', dateLabel(user.created_at)], ['Role', user.roles.map(readable).join(', ')], ['Status', <StatusBadge status={user.status} />]]} /></DataCard></div><DataCard title="Account access"><p className="ad-card-subtitle">Changes are submitted to the server for authorization. The updated account state is reloaded after confirmation.</p><div className="ad-action-row"><Button variant="secondary" onClick={() => setAction('ACTIVE')}>Activate user</Button><Button variant="danger" onClick={() => setAction('INACTIVE')}>Deactivate user</Button></div></DataCard>{action && <ConfirmationModal title={action === 'ACTIVE' ? 'Activate user?' : 'Deactivate user?'} confirm={action === 'ACTIVE' ? 'Activate user' : 'Deactivate user'} danger={action !== 'ACTIVE'} onClose={() => setAction(null)} action={() => adminUpdateUserStatus(id, { status: action })} success="User status updated successfully." onSuccess={resource.retry}><p>{action === 'ACTIVE' ? 'Request account access for' : 'This will prevent the following user from accessing FitiGo:'} <strong>{personName(user)}</strong>.</p>{action !== 'ACTIVE' && <Alert tone="warning">This changes platform access, including any owner or administrator roles assigned to this account.</Alert>}</ConfirmationModal>}</>}</Resource></>
}