import { useState } from 'react'
import { useResource } from '../../hooks/useResource'
import { gymService } from '../../services/gymService'
import { getStoredLocation } from '../../screens/NearbyGyms/LocationStore'
import { useDebouncedValue } from '../../screens/NearbyGyms/useDebouncedValue'
import GymCard from '../../components/gym/GymCard'
import Icon from '../../components/common/Icon'
import { Button, EmptyState, ErrorState, Heading, Link, Modal, Skeleton } from '../../components/common/UI'
import { navigate } from '../../router'

export default function DiscoveryPage({ home = false }: { home?: boolean }) {
  const [search, setSearch] = useState(() => new URLSearchParams(window.location.search).get('q') ?? '')
  const [category, setCategory] = useState('')
  const [sort, setSort] = useState('recommended')
  const [open, setOpen] = useState(false)
  const [rating, setRating] = useState('')
  const [openNow, setOpenNow] = useState(false)
  const [radius, setRadius] = useState('')
  const [facilities, setFacilities] = useState<number[]>([])
  const [page, setPage] = useState(1)
  const location = getStoredLocation()
  const query = useDebouncedValue(search, 300)
  const params = { search: query, gym_type: category, sort_by: sort, page, page_size: home ? 8 : 12, latitude: location?.latitude, longitude: location?.longitude, radius_km: radius ? Number(radius) : undefined, min_rating: rating ? Number(rating) : undefined, open_now: openNow || undefined, facilities }
  const result = useResource(() => gymService.discover(params), JSON.stringify(params))
  const types = useResource(gymService.types, 'gym-types')
  const amenities = useResource(gymService.facilities, 'facilities')
  const reset = () => { setSearch(''); setCategory(''); setRating(''); setOpenNow(false); setRadius(''); setFacilities([]); setPage(1) }
  const count = Number(!!rating) + Number(openNow) + Number(!!radius) + facilities.length
  return <>
    {home ? <section className="fg-hero"><div className="fg-hero-copy"><span className="fg-eyebrow"><span className="fg-dot" /> A LITTLE CLOSER TO A STRONGER YOU</span><h1>Your next workout.<br /><em>Your kind of place.</em></h1><p>Discover great gyms, find your flow, and make<br className="fg-desktop-only" /> fitness fit your life. No long-term commitments.</p><form className="fg-hero-search" onSubmit={e => { e.preventDefault(); navigate(`/explore/search?q=${encodeURIComponent(search)}`) }}><Icon name="search" /><input aria-label="Search gyms or classes" placeholder="Search gyms or classes" value={search} onChange={e => { setSearch(e.target.value); setPage(1) }} /><Button type="submit">Explore <Icon name="arrow" size={18} /></Button></form><div className="fg-hero-benefits"><span><Icon name="check" size={16} />Pay per visit</span><span><Icon name="check" size={16} />Your schedule</span><span><Icon name="check" size={16} />Easy QR entry</span></div></div><div className="fg-hero-art"><div className="fg-art-ring" /><div className="fg-art-bar"><i /><i /><b /><i /><i /></div><div className="fg-hero-label"><Icon name="spark" /><div><strong>Make room for you.</strong><span>One workout at a time.</span></div></div><span className="fg-art-caption">MOVE WITH PURPOSE.</span></div></section> : <Heading eyebrow="FIND YOUR FIT" title="Explore gyms" subtitle={location ? `Great places to work out around ${location.location_name}.` : 'Find a space that moves you. Choose a location for nearby results.'} />}
    {home && <div className="fg-quick-links"><Link to="/explore"><span className="fg-quick-icon"><Icon name="gym" /></span><div><strong>Drop in. Work out.</strong><span>Discover gyms & day visits</span></div><Icon name="arrow" /></Link><Link to="/profile/membership"><span className="fg-quick-icon"><Icon name="ticket" /></span><div><strong>Build your routine</strong><span>Find your gym membership</span></div><Icon name="arrow" /></Link><Link to="/access/qr"><span className="fg-quick-icon"><Icon name="qr" /></span><div><strong>Already a member?</strong><span>Your gym access, one tap away</span></div><Icon name="arrow" /></Link></div>}
    <section className="fg-discovery"><div className="fg-section-heading"><div><span className="fg-eyebrow">A SPACE FOR EVERY PACE</span><h2>{home ? (location ? 'Gyms near you' : 'Find your next workout') : 'Find your workout space'}</h2><p>{location ? location.location_name : 'Explore our partner gyms'} · {result.loading ? 'Finding your fit…' : `${result.data?.total_count ?? 0} places to get moving`}</p></div>{home && <Link to="/explore" className="fg-inline-link">View all gyms <Icon name="arrow" size={18} /></Link>}</div>
      {!home && <label className="fg-search"><Icon name="search" /><input placeholder="Search gyms or classes" aria-label="Search gyms or classes" value={search} onChange={e => { setSearch(e.target.value); setPage(1) }} /></label>}
      <div className="fg-filter-toolbar"><div className="fg-category-scroll"><button className={`fg-chip ${!category ? 'is-active' : ''}`} onClick={() => { setCategory(''); setPage(1) }}><Icon name="gym" size={17} />All workouts</button>{(types.data ?? []).filter(t => t !== 'All Gym Types').slice(0, 7).map(type => <button className={`fg-chip ${category === type ? 'is-active' : ''}`} key={type} onClick={() => { setCategory(type); setPage(1) }}>{type}</button>)}</div><Button variant="secondary" onClick={() => setOpen(true)}><Icon name="filter" size={17} />Filters{count ? ` (${count})` : ''}</Button></div>
      <div className="fg-results-meta"><span>{query ? `Results for “${query}”` : 'A good workout starts with the right place.'}</span><label>Sort by <select aria-label="Sort gyms" value={sort} onChange={e => { setSort(e.target.value); setPage(1) }}><option value="recommended">Recommended</option><option value="rating">Top rated</option><option value="distance" disabled={!location}>Nearest first</option></select></label></div>
      {result.loading ? <Skeleton cards={home ? 4 : 6} /> : result.error ? <ErrorState message={result.error} retry={result.retry} /> : !result.data?.gyms.length ? <EmptyState title="No gyms found" description="Try changing your location or filters." action={<Button variant="secondary" onClick={reset}>Clear filters</Button>} /> : <div className="fg-gym-grid">{result.data.gyms.map(gym => <GymCard gym={gym} key={gym.gym_id} />)}</div>}
      {!home && result.data && <div className="fg-pagination"><Button variant="secondary" disabled={page === 1} onClick={() => setPage(p => p - 1)}>Previous</Button><span>Page {page}</span><Button variant="secondary" disabled={!result.data.has_more} onClick={() => setPage(p => p + 1)}>Next</Button></div>}
    </section>
    {home && <section className="fg-membership-banner"><div><span className="fg-eyebrow">SHOW UP FOR YOURSELF</span><h2>Find a gym. Make it your own.</h2><p>Explore memberships at places you’ll love coming back to.</p><Link to="/explore" className="fg-button fg-button--primary">Explore memberships <Icon name="arrow" size={18} /></Link></div><div className="fg-banner-icon"><Icon name="ticket" size={100} /></div></section>}
    {open && <Modal title="Make it your workout" onClose={() => setOpen(false)}><div className="fg-stack"><label className="fg-field">Distance<select disabled={!location} value={radius} onChange={e => { setRadius(e.target.value); setPage(1) }}><option value="">Any distance</option>{[2, 5, 10, 25].map(n => <option key={n} value={n}>Within {n} km</option>)}</select>{!location && <small>Choose a location to filter by distance.</small>}</label><label className="fg-field">Minimum rating<select value={rating} onChange={e => { setRating(e.target.value); setPage(1) }}><option value="">Any rating</option><option value="4">4 stars and up</option><option value="4.5">4.5 stars and up</option></select></label><label className="fg-checkbox"><input type="checkbox" checked={openNow} onChange={e => { setOpenNow(e.target.checked); setPage(1) }} />Open now</label><fieldset><legend>Facilities</legend>{amenities.error ? <ErrorState message={amenities.error} retry={amenities.retry} /> : amenities.loading ? <p>Loading facilities…</p> : <div className="fg-facility-options">{amenities.data?.map(f => <label key={f.id} className="fg-checkbox"><input type="checkbox" checked={facilities.includes(f.id)} onChange={e => { setFacilities(prev => e.target.checked ? [...prev, f.id] : prev.filter(id => id !== f.id)); setPage(1) }} />{f.name}</label>)}</div>}</fieldset><Button onClick={() => setOpen(false)}>Show gyms</Button><Button variant="text" onClick={reset}>Reset filters</Button></div></Modal>}
  </>
}