import { useState } from 'react'
import { gymService } from '../../services/gymService'
import { money } from '../../services/client'
import { useResource } from '../../hooks/useResource'
import Icon from '../../components/common/Icon'
import { Alert, Badge, Button, EmptyState, ErrorState, Heading, Image, Link, Skeleton } from '../../components/common/UI'

export default function GymPage({ gymId }: { gymId: number }) {
  const result = useResource(() => gymService.details(gymId), String(gymId))
  const [tab, setTab] = useState('Overview')
  const [image, setImage] = useState(0)
  const [shareMessage, setShareMessage] = useState('')
  if (result.loading) return <Skeleton cards={2} />
  if (result.error) return <ErrorState message={result.error} retry={result.retry} />
  const gym = result.data!
  return <div className="fg-stack"><div className="fg-row"><Link to="/explore" className="fg-inline-link"><Icon name="back" size={18} />Back to gyms</Link><Button variant="secondary" onClick={async () => { try { if (navigator.share) await navigator.share({ title: gym.gym_name, url: window.location.href }); else { await navigator.clipboard.writeText(window.location.href); setShareMessage('Gym link copied.') } } catch (error) { if (!(error instanceof DOMException && error.name === 'AbortError')) setShareMessage('Unable to share. Copy the page address from your browser.') } }}><Icon name="share" size={17} />Share</Button></div>{shareMessage && <p role="status">{shareMessage}</p>}
    <div className="fg-two-column"><div className="fg-stack"><div className="fg-gallery"><Image src={gym.images[image]?.image_url} alt={gym.images[image]?.alt_text || gym.gym_name} />{gym.images.length > 1 && <div className="fg-gallery-controls"><Button variant="text" aria-label="Previous image" onClick={() => setImage(i => (i - 1 + gym.images.length) % gym.images.length)}><Icon name="back" size={16} /></Button>{image + 1} / {gym.images.length}<Button variant="text" aria-label="Next image" onClick={() => setImage(i => (i + 1) % gym.images.length)}><Icon name="arrow" size={16} /></Button></div>}</div>
    <div className="fg-panel"><div className="fg-tabs" aria-label="Gym details">{['Overview', 'Facilities', 'Classes', 'Reviews'].map(item => <button key={item} className={tab === item ? 'is-active' : ''} aria-pressed={tab === item} onClick={() => setTab(item)}>{item}</button>)}</div>
      {tab === 'Overview' && <div className="fg-stack"><h2>A little about this space</h2><p className="fg-prose">{gym.description || 'Explore the facilities and available visits at this FitiGo partner gym.'}</p>{gym.important_information.length > 0 && <><h3>Before you visit</h3><ul className="fg-prose">{gym.important_information.map((info, i) => <li key={i}>{info}</li>)}</ul></>}{gym.rules.length > 0 && <><h3>Gym policies</h3><ul className="fg-prose">{gym.rules.map((rule, i) => <li key={i}>{rule}</li>)}</ul></>}<h3>Opening hours</h3>{gym.opening_hours.weekly.map(day => <div className="fg-row" key={day.day_of_week}><span>{['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][day.day_of_week]}</span><span className="fg-muted">{day.is_closed ? 'Closed' : `${day.open_time?.slice(0, 5)} – ${day.close_time?.slice(0, 5)}`}</span></div>)}</div>}
      {tab === 'Facilities' && (gym.amenities.length ? <div className="fg-detail-facilities">{gym.amenities.map(a => <span key={a.amenity_id}><Icon name="check" size={18} />{a.amenity_name}</span>)}</div> : <EmptyState title="Facilities not listed yet" description="Contact the gym for details before your visit." />)}
      {tab === 'Classes' && (gym.classes_nearby.length ? <div className="fg-stack">{gym.classes_nearby.map(c => <div key={c.class_id} className="fg-panel fg-stack"><h3>{c.title}</h3><p className="fg-muted">{new Date(c.start_at).toLocaleString()} · {Math.max(0, c.capacity - c.filled)} seats available</p><Link to={`/gyms/${gymId}/book/access?type=CLASS`} className="fg-inline-link">View class sessions <Icon name="arrow" size={17} /></Link></div>)}</div> : <EmptyState title="No upcoming classes" description="You can still explore gym access for your next workout." />)}
      {tab === 'Reviews' && (gym.reviews.length ? <div>{gym.reviews.map(r => <article className="fg-review" key={r.review_id}><div className="fg-row"><strong>{r.user_display_name}</strong><span className="fg-rating"><Icon name="star" size={16} />{r.rating} / 5</span></div><small className="fg-muted">{new Date(r.created_at).toLocaleDateString()}</small>{r.comment && <p>{r.comment}</p>}</article>)}</div> : <EmptyState title="A fresh start" description="No reviews yet. Reviews appear after verified visits." />)}
    </div></div><aside className="fg-panel fg-stack fg-sidebar-sticky"><Badge tone={gym.opening_hours.open_now ? 'success' : 'neutral'}>{gym.opening_hours.open_now == null ? 'Partner gym' : gym.opening_hours.open_now ? 'Open now' : 'Closed now'}</Badge><Heading title={gym.gym_name} subtitle={[gym.location.locality, gym.location.city].filter(Boolean).join(', ')} /><div className="fg-rating"><Icon name="star" />{gym.ratings.average_rating != null ? gym.ratings.average_rating.toFixed(1) : 'New'}<span className="fg-muted"> · {gym.ratings.review_count} reviews</span></div><p className="fg-muted">{gym.location.full_address}</p>{gym.opening_hours.open_today && <p><Icon name="clock" size={15} /> {gym.opening_hours.open_today}</p>}<hr className="fg-divider" /><h3>Your workout, your way</h3>{gym.membership_access.day_pass_price != null ? <p><span className="fg-price">{money(gym.membership_access.day_pass_price)}</span> / visit</p> : <p className="fg-muted">Choose a date to see your visit price.</p>}{gym.membership_access.status === 'UNAVAILABLE' ? <Alert>This gym is currently unavailable for booking.</Alert> : <Link to={`/gyms/${gymId}/book/access`} className="fg-button fg-button--primary">Book a visit <Icon name="arrow" size={18} /></Link>}<Link to={`/gyms/${gymId}/membership`} className="fg-button fg-button--secondary">View memberships</Link><small className="fg-muted">Availability and final pricing are confirmed before payment.</small></aside></div>
    {gym.membership_access.status !== 'UNAVAILABLE' && <div className="fg-mobile-book"><span><strong>Your next workout</strong><small>{gym.gym_name}</small></span><Link to={`/gyms/${gymId}/book/access`} className="fg-button fg-button--primary">Book a visit</Link></div>}
  </div>
}