import AccessQr from '../../components/AccessQr'
import { accessService } from '../../services/accountService'
import { useMembershipResource } from '../../hooks/useMembershipResource'
import { useAccessQr } from '../../hooks/useAccessQr'
import { membershipDate, membershipTime, todayFrom, utcTimestamp } from '../../utils/membership'
import { Button, Heading, Link, Skeleton } from '../../components/common/UI'
import Icon from '../../components/common/Icon'
import { DailyAccessCard, MembershipBack, MembershipNotice, MembershipPanel, MembershipResource, MembershipStatusBadge } from '../../components/membership/MembershipUI'

export default function AccessPage() {
  const rawId = new URLSearchParams(window.location.search).get('gymId')
  const gymId = Number(rawId)
  return <div className="fm-page fm-narrow"><MembershipBack /><Heading title={gymId ? 'Your Access QR' : 'Today’s Access'} subtitle={gymId ? 'Your workout starts at the entrance.' : 'One daily access. A fresh opportunity to move.'} />{Number.isSafeInteger(gymId) && gymId > 0 ? <QrCard key={gymId} gymId={gymId} /> : <AccessOverview />}</div>
}
function AccessOverview() {
  const resource = useMembershipResource(accessService.current, 'access-overview')
  return <MembershipResource resource={resource}>{calendar => <DailyAccessCard calendar={calendar} refresh={resource.retry} />}</MembershipResource>
}
function QrCard({ gymId }: { gymId: number }) {
  const state = useAccessQr(gymId)
  const day = state.calendar ? todayFrom(state.calendar) : undefined
  if (state.loading) return <Skeleton cards={1} />
  if (state.error) return <MembershipPanel><div className="fm-centered"><span className="fm-icon fm-icon--large"><Icon name="shield" size={30} /></span><h2>{state.code === 'GYM_NOT_ELIGIBLE' ? 'This gym isn’t included' : state.code?.includes('ALREADY') ? 'Today’s Access Already Used' : state.code === 'MEMBERSHIP_PAUSED' ? 'Membership paused' : state.code === 'MEMBERSHIP_EXPIRED' ? 'Membership expired' : 'Unable to generate QR'}</h2><p role="alert">{state.error}</p><Button onClick={() => void state.refresh()}>Retry</Button><Link to={state.code === 'GYM_NOT_ELIGIBLE' ? '/gyms' : '/membership'} className="fg-button fg-button--secondary">{state.code === 'GYM_NOT_ELIGIBLE' ? 'Choose Another Gym' : 'View Membership'}</Link><Link to={`/gyms/${gymId}/visit`} className="fm-back">Back</Link></div></MembershipPanel>
  if (state.checkedIn) return <MembershipPanel><div className="fm-centered fm-checkin-success"><span className="fm-success-icon"><Icon name="check" size={40} /></span><h2>Check-in Successful!</h2><p>Your workout is officially underway.</p><strong>{state.access?.status === 'USED' ? state.access.gym_name : day?.gym_name}</strong>{day && <p>{membershipDate(day.date)}{day.checkin_time ? ` · ${day.checkin_time.slice(0, 5)} UTC` : ''}</p>}<MembershipStatusBadge status="USED" /><p className="fm-muted">Today’s access has been used. Check your next daily access tomorrow; your membership must still be eligible.</p><Link to="/membership" className="fg-button fg-button--primary fm-full">View Membership</Link><Link to="/home" className="fg-button fg-button--secondary fm-full">Back to Home</Link></div></MembershipPanel>
  if (state.access?.status === 'USED') return <MembershipPanel><div className="fm-centered"><span className="fm-icon fm-icon--large"><Icon name="check" size={30} /></span><h2>Today’s Access Already Used</h2><p>You have already used your FitiGo access today.</p><strong>{state.access.gym_name}</strong><p>{membershipDate(state.access.used_at)} · {membershipTime(state.access.used_at)} UTC</p><MembershipStatusBadge status="USED" /><Link to="/membership" className="fg-button fg-button--primary fm-full">View Membership</Link><Link to="/home" className="fg-button fg-button--secondary fm-full">Back to Home</Link></div></MembershipPanel>
  if (state.access && state.access.status !== 'ACTIVE') return <MembershipPanel><div className="fm-centered"><MembershipStatusBadge status={state.access.status} /><h2>{state.access.status === 'PAUSED' ? 'Membership paused' : state.access.status === 'EXPIRED' ? 'Membership expired' : 'No access available'}</h2><p>{state.access.status === 'PAUSED' ? 'Gym access is unavailable during a pause. Your daily access is not consumed.' : 'FitiGo has not issued access for today. Check your membership for more information.'}</p><Link to="/membership" className="fg-button fg-button--primary">View Membership</Link></div></MembershipPanel>
  if (state.needsRefresh) return <MembershipPanel><div className="fm-centered"><Icon name="qr" size={40} /><h2>Refresh your access QR</h2><p>Your QR was hidden or reached its server-provided expiry. Check your access again before entering.</p><Button onClick={() => void state.refresh()}>Refresh access</Button><Link to="/membership">View Membership</Link></div></MembershipPanel>
  if (state.access?.status === 'ACTIVE') {
    const expires = Date.parse(utcTimestamp(state.access.expires_at))
    if (!Number.isFinite(expires) || expires <= state.clock) return <MembershipPanel><h2>Your QR needs refreshing</h2><Button onClick={() => void state.refresh()}>Refresh access</Button></MembershipPanel>
    return <MembershipPanel className="fm-qr-card"><div className="fm-centered"><MembershipStatusBadge status="AVAILABLE" /><h2>{state.gym?.gym_name}</h2><p className="fm-muted">{[state.gym?.location.locality, state.gym?.location.city].filter(Boolean).join(', ')}</p><div className="fm-qr-frame"><AccessQr token={state.access.qr_token} /></div><strong>Show this QR to gym staff</strong><p className="fm-qr-validity"><Icon name="clock" size={17} />Valid for today only</p><p>This QR can only be used once today.</p><small className="fm-muted">QR expires at {membershipTime(state.access.expires_at)} UTC · {Math.max(0, Math.ceil((expires - state.clock) / 1000))} seconds remaining</small></div><MembershipNotice>Keep this screen open while staff scan. We check for a recorded check-in automatically. Never share your personal access QR.</MembershipNotice>{state.access.access_type === 'MULTI_GYM' && <p className="fm-footnote">The backend issues an account-wide multi-gym QR, not a gym-bound reservation. Staff validate entry for the scanning gym.</p>}<Link to={`/gyms/${gymId}/visit`} className="fg-button fg-button--secondary fm-full">Back to visit details</Link></MembershipPanel>
  }
  return state.calendar ? <DailyAccessCard calendar={state.calendar} refresh={() => void state.refresh()} /> : <MembershipPanel><h2>Unable to load your access</h2><Button onClick={() => void state.refresh()}>Retry</Button></MembershipPanel>
}