import { useState } from 'react'
import { accessService, type AccessDay } from '../../services/accountService'
import { useMembershipResource } from '../../hooks/useMembershipResource'
import { accessLabels, dayPresentation, membershipDate } from '../../utils/membership'
import { Button, EmptyState, Heading, Link } from '../../components/common/UI'
import Icon from '../../components/common/Icon'
import { AccessDayDetail, MembershipBack, MembershipNotice, MembershipPanel, MembershipResource, MembershipStatusBadge } from '../../components/membership/MembershipUI'

export default function MembershipCalendar({ history = false }: { history?: boolean }) {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7))
  const [year, number] = month.split('-').map(Number)
  const [selected, setSelected] = useState<AccessDay | null>(null)
  const [allActivity, setAllActivity] = useState(false)
  const resource = useMembershipResource(() => accessService.calendar(year, number), `membership-calendar:${month}`)
  const move = (offset: number) => { setSelected(null); setMonth(new Date(Date.UTC(year, number - 1 + offset, 1)).toISOString().slice(0, 7)) }
  return <div className="fm-page"><MembershipBack /><Heading title={history ? 'Visit History' : 'Membership Calendar'} subtitle={history ? 'The workouts you showed up for.' : 'Every access day has its own story.'} action={<Link to={history ? '/profile/access' : '/profile/visits'} className="fg-button fg-button--secondary"><Icon name={history ? 'calendar' : 'clock'} size={17} />{history ? 'View calendar' : 'Visit history'}</Link>} /><div className="fm-calendar-layout"><MembershipPanel><div className="fm-month-navigation"><Button variant="text" aria-label="Previous month" disabled={month === '2000-01'} onClick={() => move(-1)}><Icon name="back" /></Button><h2>{new Date(Date.UTC(year, number - 1, 1)).toLocaleDateString('en-IN', { month: 'long', year: 'numeric', timeZone: 'UTC' })}</h2><Button variant="text" aria-label="Next month" disabled={month === '2100-12'} onClick={() => move(1)}><Icon name="arrow" /></Button></div><MembershipResource resource={resource}>{calendar => history ? <><div className="fm-filter-chips" role="group" aria-label="History display"><button type="button" aria-pressed={!allActivity} onClick={() => setAllActivity(false)}>Actual visits</button><button type="button" aria-pressed={allActivity} onClick={() => setAllActivity(true)}>All access activity</button></div><VisitHistory days={calendar.days} all={allActivity} /></> : <><p className="fm-muted fm-calendar-caption">{calendar.gym?.name || 'Your membership access'} · UTC</p><div className="fm-calendar" role="group" aria-label="Membership access days"><div className="fm-calendar-week" aria-hidden="true">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(label => <span key={label}>{label}</span>)}</div><div className="fm-calendar-days">{Array.from({ length: (new Date(Date.UTC(year, number - 1, 1)).getUTCDay() + 6) % 7 }, (_, index) => <span key={`blank-${index}`} aria-hidden="true" />)}{calendar.days.map(day => {
      const state = dayPresentation(day)
      return <button type="button" key={day.date} className={`fm-day fm-day--${state.toLowerCase()} ${day.status === 'TODAY' ? 'fm-day--today' : ''}`} aria-pressed={selected?.date === day.date} aria-label={`${membershipDate(day.date)}${day.status === 'TODAY' ? ', Today' : ''}: ${accessLabels[state]}`} onClick={() => setSelected(day)}><span>{Number(day.date.slice(-2))}</span><span className="fm-day-symbol" aria-hidden="true">{state === 'VISITED' ? '✓' : state === 'USED' ? '✓' : state === 'PAUSED' ? 'Ⅱ' : state === 'CONSUMED' ? '−' : state === 'AVAILABLE' ? '•' : ''}</span></button>
    })}</div></div><div className="fm-calendar-legend">{[{ state: 'visited', label: 'Visited', symbol: '✓' }, { state: 'available', label: 'Available', symbol: '•' }, { state: 'consumed', label: 'No visit / consumed', symbol: '−' }, { state: 'paused', label: 'Paused', symbol: 'Ⅱ' }, { state: 'today', label: 'Today', symbol: '○' }].map(item => <span key={item.state}><i className={`fm-day--${item.state}`}>{item.symbol}</i>{item.label}</span>)}</div>{selected ? <AccessDayDetail day={selected} /> : <p className="fm-calendar-help">Select a date to see its access state and any recorded visit.</p>}</>}</MembershipResource></MembershipPanel><aside className="fm-stack"><MembershipPanel title="A little clarity"><div className="fm-explainer"><span className="fm-explainer-symbol fm-day--visited">✓</span><div><h3>Visited</h3><p>An actual, validated gym check-in.</p></div></div><div className="fm-explainer"><span className="fm-explainer-symbol fm-day--consumed">−</span><div><h3>No visit · Access consumed</h3><p>An active day ended without a visit. Daily access does not carry forward.</p></div></div><div className="fm-explainer"><span className="fm-explainer-symbol fm-day--paused">Ⅱ</span><div><h3>Paused</h3><p>A pause recorded by FitiGo. Gym access was unavailable and daily access was not consumed.</p></div></div><MembershipNotice>Dates and states come from your account’s access calendar. This calendar combines your memberships; it does not infer access for future dates.</MembershipNotice></MembershipPanel></aside></div></div>
}
function VisitHistory({ days, all }: { days: AccessDay[]; all: boolean }) {
  const rows = days.filter(day => all ? ['VISITED', 'USED', 'CONSUMED', 'PAUSED', 'EXPIRED'].includes(dayPresentation(day)) : dayPresentation(day) === 'VISITED').slice().reverse()
  if (!rows.length) return <EmptyState title={all ? 'No access activity this month' : 'No visits yet'} description={all ? 'Use the month controls to view another period.' : 'Your validated gym visits will appear here. Unused access days are shown separately under All access activity.'} />
  return <div className="fm-history-list">{rows.map(day => <article key={day.date}><span className={`fm-history-icon fm-day--${dayPresentation(day).toLowerCase()}`}><Icon name={dayPresentation(day) === 'VISITED' ? 'check' : 'calendar'} size={21} /></span><div><small>{membershipDate(day.date)}</small><h3>{dayPresentation(day) === 'VISITED' ? day.gym_name || 'Gym visit' : accessLabels[dayPresentation(day)]}</h3>{day.checkin_time && <p>{day.checkin_time.slice(0, 5)} UTC</p>}<MembershipStatusBadge status={dayPresentation(day) === 'VISITED' ? 'CHECKED_IN' : dayPresentation(day)} /></div></article>)}</div>
}