import { useEffect, useState } from 'react'
import { bookingCancel, bookingMarkAttended, bookingMarkNoShow, listBookings, type OwnerBooking } from '../screens/GymOwner/api'
import { useMutation, useResource } from '../hooks/useResource'
import { useOwner } from './context'
import { allowedBookingActions, capabilities, customerName, ownerService } from './services'
import { Breadcrumbs, Button, Card, ConfirmDialog, EmptyState, ErrorState, Field, Input, Link, Notice, PageHeader, Pagination, Skeleton, StatusBadge } from './UI'
import { dateLabel, localDate, money } from '../services/client'
import Icon from '../components/common/Icon'

export function BookingTable({ bookings, compact = false }: { bookings: OwnerBooking[]; compact?: boolean }) {
  return <><div className="ow-table-desktop"><table className="ow-table"><thead><tr><th>{compact ? 'Time' : 'Date / time'}</th><th>Customer</th><th>Booking</th>{!compact && <th>Amount</th>}<th>Status</th><th><span className="srOnly">Actions</span></th></tr></thead><tbody>{bookings.map(b => <tr key={b.id}><td>{!compact && <strong>{dateLabel(b.slot_date)}</strong>}<span>{b.slot.start_time.slice(0, 5)}</span></td><td><strong>{customerName(b.customer)}</strong><small>{b.quantity} {b.quantity === 1 ? 'person' : 'people'}</small></td><td><strong>{b.slot.name}</strong><small>#{b.id} · {b.payment?.status.replace(/_/g, ' ').toLowerCase() || 'Payment not recorded'}</small></td>{!compact && <td>{money(b.total_price, b.currency)}</td>}<td><StatusBadge status={b.attendance_status || b.status} /></td><td><Link to={`/owner/bookings/${b.id}`} className="ow-row-action" label={`View booking ${b.id}`}><Icon name="chevron" size={18} /></Link></td></tr>)}</tbody></table></div><div className="ow-mobile-cards">{bookings.map(b => <Link to={`/owner/bookings/${b.id}`} className="ow-booking-card" key={b.id}><div><strong>{customerName(b.customer)}</strong><StatusBadge status={b.attendance_status || b.status} /></div><p>{b.slot.name} · {b.quantity} {b.quantity === 1 ? 'person' : 'people'}</p><div><span>{!compact && `${dateLabel(b.slot_date)} · `}{b.slot.start_time.slice(0, 5)}</span><strong>{money(b.total_price, b.currency)}</strong></div><small>#{b.id} · {b.payment?.status || 'Payment not recorded'}</small></Link>)}</div></>
}
export default function Bookings({ id }: { id?: number }) { return id ? <BookingDetail id={id} /> : <BookingList /> }
function BookingList() {
  const { gymId, gym } = useOwner()
  const [date, setDate] = useState(new URLSearchParams(location.search).get('date') || localDate())
  const [page, setPage] = useState(0)
  const [search, setSearch] = useState(''); const [debounced, setDebounced] = useState(''); const [payment, setPayment] = useState(''); const [status, setStatus] = useState('')
  useEffect(() => { const timer = setTimeout(() => setDebounced(search), 250); return () => clearTimeout(timer) }, [search])
  const resource = useResource(() => gymId ? listBookings(gymId, { date: date || undefined, limit: 20, offset: page * 20 }) : Promise.resolve([]), `bookings:${gymId}:${date}:${page}`)
  const filtered = resource.data?.filter(b => (!debounced || `${customerName(b.customer)} ${b.id}`.toLowerCase().includes(debounced.toLowerCase())) && (!payment || b.payment?.status === payment) && (!status || b.status === status)) || []
  return <div className="ow-stack"><PageHeader title="Bookings" description={gym ? `Every visit, in one place · ${gym.name}` : 'Select a gym to view its bookings.'} /><Card><div className="ow-toolbar"><Input label="Booking date" type="date" value={date} onChange={e => { setDate(e.target.value); setPage(0) }} /><Button variant="secondary" onClick={() => { setDate(localDate()); setPage(0) }}>Today</Button><Button variant="text" onClick={() => { setDate(''); setPage(0) }}>All dates</Button><Input label="Search this page" placeholder="Customer or booking ID" value={search} onChange={e => setSearch(e.target.value)} /><Field label="Status on this page"><select value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{Array.from(new Set(resource.data?.map(b => b.status))).map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Payment on this page"><select value={payment} onChange={e => setPayment(e.target.value)}><option value="">All payments</option>{Array.from(new Set(resource.data?.flatMap(b => b.payment ? [b.payment.status] : []))).map(s => <option key={s}>{s}</option>)}</select></Field></div>{!gymId ? <EmptyState title="Select a gym" action={<Link to="/owner/gyms">View gyms</Link>} /> : resource.loading ? <Skeleton /> : resource.error ? <ErrorState message={resource.error} retry={resource.retry} /> : <>{filtered.length ? <BookingTable bookings={filtered} /> : <EmptyState title={resource.data?.length ? 'No matching bookings on this page' : 'No bookings yet'} description="Try another date or clear your filters." />}<Pagination page={page} hasMore={resource.data?.length === 20} onChange={setPage} /></>}</Card></div>
}
function BookingDetail({ id }: { id: number }) {
  const resource = useResource(() => ownerService.booking(id), `booking:${id}`)
  const { gyms, syncGym, gymId, toast } = useOwner()
  const mutation = useMutation(); const [action, setAction] = useState<'MARK_ATTENDED' | 'MARK_NO_SHOW' | 'CANCEL' | null>(null); const [note, setNote] = useState('')
  useEffect(() => { if (resource.data && resource.data.gym_id !== gymId && gyms.some(g => g.id === resource.data?.gym_id)) syncGym(resource.data.gym_id) }, [resource.data?.gym_id, gyms, gymId])
  if (resource.loading) return <Skeleton />
  if (resource.error) return <ErrorState message={resource.error} retry={resource.retry} />
  const b = resource.data!; const actions = allowedBookingActions(b)
  return <div className="ow-stack"><Breadcrumbs items={[{ label: 'Bookings', to: '/owner/bookings' }, { label: `#${id}` }]} /><PageHeader title={`Booking #${id}`} description={`${customerName(b.customer)} · ${dateLabel(b.slot_date)}`} action={<StatusBadge status={b.status} />} /><Card title="Visit details"><dl className="ow-details">{[['Customer', customerName(b.customer)], ['Gym', gyms.find(g => g.id === b.gym_id)?.name || `Gym #${b.gym_id}`], ['Class / slot', b.slot.name], ['Time', `${b.slot.start_time.slice(0, 5)} – ${b.slot.end_time.slice(0, 5)}`], ['People', b.quantity], ['Amount', money(b.total_price, b.currency)], ['Created', dateLabel(b.created_at)], ['Attendance recorded', b.attendance_marked_at ? new Date(b.attendance_marked_at).toLocaleString() : 'Not recorded']].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="ow-actions"><StatusBadge status={b.payment?.status || 'NOT_RECORDED'} />{b.attendance_status && <StatusBadge status={b.attendance_status} />}</div></Card>{actions.length ? <Card title="Booking actions"><div className="ow-actions">{actions.map(a => <Button key={a} variant={a === 'CANCEL' ? 'danger' : 'secondary'} onClick={() => setAction(a)}>{a === 'CANCEL' ? 'Cancel booking' : a === 'MARK_ATTENDED' ? 'Mark attended' : 'Mark no-show'}</Button>)}</div></Card> : <Notice>{capabilities.bookingActions.message}</Notice>}{action && <ConfirmDialog title={action === 'CANCEL' ? 'Cancel booking?' : 'Record attendance?'} label="Confirm update" destructive={action === 'CANCEL'} pending={mutation.pending} error={mutation.error} onClose={() => setAction(null)} onConfirm={() => void mutation.run(async () => { if (action === 'CANCEL') await bookingCancel(id, note); else if (action === 'MARK_ATTENDED') await bookingMarkAttended(id, note); else await bookingMarkNoShow(id, note); setAction(null); resource.retry(); toast('Booking updated.') })}>{action === 'CANCEL' ? b.cancellation_policy || 'The server will validate this request. No refund amount is estimated here.' : 'Record the selected attendance outcome for this booking.'}<Input label="Note (optional)" value={note} onChange={e => setNote(e.target.value)} /></ConfirmDialog>}</div>
}