import { useEffect, useRef, useState } from 'react'
import * as api from '../screens/GymOwner/api'
import { useMutation, useResource } from '../hooks/useResource'
import { useOwner } from './context'
import { Breadcrumbs, Button, Card, ConfirmDialog, EmptyState, ErrorState, Field, Input, Link, Notice, PageHeader, Skeleton, StatusBadge } from './UI'
import { Image } from '../components/common/UI'
import Icon from '../components/common/Icon'
import { dateLabel, money } from '../services/client'
import { capabilities } from './services'
import { navigate } from '../router'

const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
const steps = ['Basic details', 'Location', 'Pricing', 'Photos', 'Facilities', 'Operating hours', 'Review']
export default function Gyms({ gymId, form = false }: { gymId?: number; form?: boolean }) {
  if (form) return <GymFormLoader gymId={gymId} />
  if (gymId) return <GymDetails gymId={gymId} />
  return <GymList />
}
function GymList() {
  const { gyms } = useOwner()
  return <div className="ow-stack"><PageHeader title="My gyms" description="Your spaces. Your community. Manage them all here." action={<Link className="fg-button fg-button--primary" to="/owner/gyms/create"><Icon name="plus" />Add gym</Link>} />{!gyms.length ? <Card><EmptyState title="No gyms yet" description="Create your first gym and submit it for approval." action={<Link className="fg-button fg-button--primary" to="/owner/gyms/create">Create gym</Link>} /></Card> : <div className="ow-card-grid">{gyms.map(g => <article key={g.id} className="ow-card ow-gym-card"><Image src={g.cover_image_url} alt={g.name} /><div className="ow-stack"><StatusBadge status={g.status === 'APPROVED' && !g.is_active ? 'INACTIVE' : g.status || 'UNKNOWN'} /><h2>{g.name}</h2><p className="ow-muted"><Icon name="pin" size={16} /> {g.city || 'Location not configured'}</p><div className="ow-actions"><Link className="fg-button fg-button--secondary" to={`/owner/gyms/${g.id}`}>Manage gym<Icon name="arrow" size={16} /></Link>{g.status === 'APPROVED' && g.is_active && <Link className="ow-text-link" to={`/gyms/${g.id}`}>View on FitiGo</Link>}</div></div></article>)}</div>}</div>
}
function GymDetails({ gymId }: { gymId: number }) {
  const resource = useResource(() => api.fetchGymDetailsOwner(gymId), `gym:${gymId}`)
  const [tab, setTab] = useState('Overview'); const [confirm, setConfirm] = useState(false)
  const mutation = useMutation(); const { refreshGyms, toast } = useOwner()
  if (resource.loading) return <Skeleton />
  if (resource.error) return <ErrorState message={resource.error} retry={resource.retry} />
  const gym = resource.data!; const image = gym.images.find(i => i.is_cover) || gym.images[0]
  return <div className="ow-stack"><Breadcrumbs items={[{ label: 'My gyms', to: '/owner/gyms' }, { label: gym.name }]} /><PageHeader title={gym.name} description={[gym.city, gym.state].filter(Boolean).join(', ')} action={<Link className="fg-button fg-button--secondary" to={`/owner/gyms/${gymId}/edit`}>{gym.status === 'DRAFT' ? 'Continue setup' : 'Edit details'}</Link>} />
    <Notice tone={gym.status === 'REJECTED' ? 'error' : gym.status === 'APPROVED' ? 'success' : 'info'}>{gym.status === 'DRAFT' ? 'Your gym is a draft. Complete your details before submitting for approval.' : gym.status === 'PENDING_APPROVAL' ? 'Your gym is being reviewed. Approval updates will appear here.' : gym.status === 'REJECTED' ? 'This gym was rejected. The owner API does not provide a rejection reason. Resubmission is not available.' : gym.status === 'APPROVED' ? gym.is_active ? 'Your gym is live on FitiGo.' : 'Your gym is approved but currently inactive.' : `Gym status: ${gym.status}`}</Notice>
    <nav className="ow-tabs" aria-label="Gym sections">{['Overview', 'Facilities', 'Photos', 'Hours', 'Pricing'].map(t => <button type="button" aria-current={tab === t ? 'page' : undefined} key={t} onClick={() => setTab(t)}>{t}</button>)}</nav>
    {tab === 'Overview' && <><Card><div className="ow-gym-overview"><Image src={image ? `/uploads/${image.file_path}` : null} alt={gym.name} /><div className="ow-stack"><StatusBadge status={gym.status} /><h2>{gym.name}</h2><p>{gym.description || 'No description added.'}</p><dl className="ow-details"><div><dt>Address</dt><dd>{[gym.address_line_1, gym.address_line_2, gym.city, gym.postal_code].filter(Boolean).join(', ') || 'Not configured'}</dd></div><div><dt>Contact</dt><dd>{gym.phone || 'No phone added'}<br />{gym.email || 'No email added'}</dd></div><div><dt>Created</dt><dd>{dateLabel(gym.created_at)}</dd></div></dl></div></div></Card><div className="ow-actions"><Link to={`/owner/gyms/${gymId}/memberships`} className="fg-button fg-button--secondary">Membership plans</Link><Link to={`/owner/gyms/${gymId}/classes`} className="fg-button fg-button--secondary">Classes & slots</Link>{gym.status === 'DRAFT' && <Button onClick={() => setConfirm(true)}>Submit for approval</Button>}{gym.status === 'APPROVED' && gym.is_active && <Link to={`/gyms/${gymId}`} className="fg-button fg-button--secondary">View on FitiGo</Link>}</div></>}
    {tab === 'Facilities' && <Card title="Facilities">{gym.facilities.length ? <div className="ow-facilities">{gym.facilities.map(f => <span className="ow-facility is-selected" key={f.id}><Icon name="check" />{f.name}</span>)}</div> : <EmptyState title="No facilities configured" />}</Card>}
    {tab === 'Photos' && <Card title="Gym photos"><Photos gym={gym} onSaved={resource.retry} /></Card>}
    {tab === 'Hours' && <Card title="Operating hours">{gym.operating_hours.length ? <div className="ow-hours">{gym.operating_hours.map(h => <div key={h.day_of_week}><strong>{days[h.day_of_week]}</strong><span>{h.is_closed ? 'Closed' : `${h.open_time?.slice(0, 5)} – ${h.close_time?.slice(0, 5)}`}</span></div>)}</div> : <EmptyState title="Operating hours not configured" />}</Card>}
    {tab === 'Pricing' && <Card title="Day pass pricing"><p className="ow-price">{gym.gym_price_per_person !== undefined ? money(gym.gym_price_per_person) : 'Not available'}<small> / person</small></p><p className="ow-muted">Membership plans and classes have separate pricing.</p></Card>}
    {confirm && <ConfirmDialog title="Submit gym for approval?" label="Submit for approval" pending={mutation.pending} error={mutation.error} onClose={() => setConfirm(false)} onConfirm={() => void mutation.run(async () => { await api.submitGymForApproval(gymId); setConfirm(false); refreshGyms(); resource.retry(); toast('Gym submitted for approval.') })}>Check that your photos, address, pricing, facilities and operating hours are ready for review. No approval timeline is guaranteed.</ConfirmDialog>}
  </div>
}
function Photos({ gym, onSaved }: { gym: api.OwnerGymDetails; onSaved: () => void }) {
  const mutation = useMutation(); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(''); const [cover, setCover] = useState(false)
  useEffect(() => { if (!file) { setPreview(''); return } const url = URL.createObjectURL(file); setPreview(url); return () => URL.revokeObjectURL(url) }, [file])
  return <div className="ow-stack"><Notice>{capabilities.photoManagement.message}</Notice><div className="ow-photo-grid">{gym.images.map(i => <figure key={i.id}><Image src={`/uploads/${i.file_path}`} alt={i.original_filename || gym.name} /><figcaption>{i.is_cover ? <StatusBadge status="COVER" /> : <Button variant="secondary" loading={mutation.pending} onClick={() => void mutation.run(async () => { await api.setCoverImage(gym.id, i.id); onSaved() })}>Set cover</Button>}</figcaption></figure>)}</div><Field label="Upload a photo" hint="JPEG, PNG or WebP. Maximum 5 MB per image."><input type="file" accept="image/jpeg,image/png,image/webp" disabled={mutation.pending} onChange={e => { const f = e.target.files?.[0]; mutation.setError(''); if (f && (!['image/jpeg', 'image/png', 'image/webp'].includes(f.type) || f.size > 5 * 1024 * 1024)) { mutation.setError('Choose a JPEG, PNG or WebP image up to 5 MB.'); e.target.value = ''; setFile(null); return } setFile(f || null) }} /></Field>{file && <div className="ow-upload-preview"><img src={preview} alt="New gym photo preview" /><span>{file.name}</span><label className="ow-check"><input type="checkbox" checked={cover} onChange={e => setCover(e.target.checked)} />Use as cover</label><Button variant="text" disabled={mutation.pending} onClick={() => setFile(null)}>Remove selection</Button><Button loading={mutation.pending} onClick={() => void mutation.run(async () => { await api.uploadGymImage(gym.id, file, cover); setFile(null); onSaved() })}>Upload photo</Button></div>}{mutation.pending && <progress aria-label="Saving photo" />}{mutation.error && <Notice tone="error">{mutation.error}</Notice>}</div>
}
function GymFormLoader({ gymId }: { gymId?: number }) {
  const resource = useResource(() => gymId ? api.fetchGymDetailsOwner(gymId) : Promise.resolve(null), `gym-form:${gymId}`)
  if (resource.loading) return <Skeleton />
  if (resource.error) return <ErrorState message={resource.error} retry={resource.retry} />
  return <GymWizard initial={resource.data} />
}
function GymWizard({ initial }: { initial: api.OwnerGymDetails | null }) {
  const [gym, setGym] = useState(initial); const [step, setStep] = useState(0); const [confirm, setConfirm] = useState(false)
  const [values, setValues] = useState({ name: initial?.name || '', description: initial?.description || '', phone: initial?.phone || '', email: initial?.email || '', address_line_1: initial?.address_line_1 || '', address_line_2: initial?.address_line_2 || '', city: initial?.city || '', state: initial?.state || '', country: initial?.country || '', postal_code: initial?.postal_code || '', latitude: initial?.latitude || '', longitude: initial?.longitude || '', gym_price_per_person: initial?.gym_price_per_person || '', has_classes: initial?.has_classes || false })
  const [facilities, setFacilities] = useState(initial?.facilities.map(f => f.id) || [])
  const [hours, setHours] = useState<api.OperatingHourItem[]>(days.map((_, i) => initial?.operating_hours.find(h => h.day_of_week === i) || { day_of_week: i, open_time: null, close_time: null, is_closed: false }))
  const [locating, setLocating] = useState(false); const alive = useRef(true)
  useEffect(() => { alive.current = true; return () => { alive.current = false } }, [])
  const facilityResource = useResource(api.fetchFacilities, 'facility-catalog')
  const mutation = useMutation(); const { refreshGyms, toast, syncGym } = useOwner(); const formRef = useRef<HTMLFormElement>(null)
  function field(key: keyof typeof values, value: string | boolean) { setValues(v => ({ ...v, [key]: value })) }
  async function saveStep() {
    let current = gym
    if (step <= 2 || !current) {
      if (!values.name.trim()) throw new Error('Enter a gym name before saving your draft.')
      const payload = { ...values, name: values.name.trim(), gym_price_per_person: values.gym_price_per_person || '0.00', latitude: values.latitude || null, longitude: values.longitude || null }
      current = current ? await api.updateGymOwner(current.id, payload) : await api.createGymOwner(payload)
      setGym(current); syncGym(current.id); refreshGyms()
      if (!initial) window.history.replaceState({}, '', `/owner/gyms/${current.id}/edit`)
    }
    if (step === 4) await api.setGymFacilities(current.id, facilities)
    if (step === 5) await api.setOperatingHours(current.id, hours)
    const updated = await api.fetchGymDetailsOwner(current.id); setGym(updated)
    return updated
  }
  const textInput = (label: string, key: keyof typeof values, extra: { required?: boolean; type?: string; maxLength?: number; minLength?: number } = {}) => <Input label={label} value={String(values[key])} onChange={e => field(key, e.target.value)} {...extra} />
  return <div className="ow-stack"><Breadcrumbs items={[{ label: 'My gyms', to: '/owner/gyms' }, { label: initial ? 'Edit gym' : 'Create gym' }]} /><PageHeader title={initial ? 'Make your gym shine' : 'Bring your gym to FitiGo'} description="A few simple steps to get your space ready for your community." /><div className="ow-wizard"><aside className="ow-wizard-steps"><span className="ow-eyebrow">GYM SETUP</span>{steps.map((label, i) => <div key={label} className={i === step ? 'is-current' : i < step ? 'is-complete' : ''}><span>{i < step ? <Icon name="check" size={16} /> : i + 1}</span><strong>{label}</strong></div>)}<p>Each completed step is saved to your gym.</p></aside><Card><div className="ow-stack"><span className="ow-eyebrow">STEP {step + 1} OF {steps.length}</span><h2>{steps[step]}</h2><form ref={formRef} className="ow-stack" onSubmit={e => { e.preventDefault(); void mutation.run(async () => { await saveStep(); setStep(s => Math.min(6, s + 1)) }) }}>
      {step === 0 && <>{textInput('Gym name', 'name', { required: true, minLength: 2, maxLength: 200 })}<Field label="Description"><textarea rows={5} maxLength={2000} value={values.description} onChange={e => field('description', e.target.value)} /></Field><div className="ow-form-grid">{textInput('Contact phone', 'phone', { type: 'tel', maxLength: 30 })}{textInput('Contact email', 'email', { type: 'email', maxLength: 255 })}</div></>}
      {step === 1 && <>{textInput('Street address', 'address_line_1', { maxLength: 255 })}{textInput('Address line 2', 'address_line_2', { maxLength: 255 })}<div className="ow-form-grid">{textInput('City', 'city', { maxLength: 100 })}{textInput('State', 'state', { maxLength: 100 })}{textInput('Postal code', 'postal_code', { maxLength: 20 })}{textInput('Country', 'country', { maxLength: 100 })}</div><Button variant="secondary" loading={locating} onClick={() => { if (!navigator.geolocation) { mutation.setError('Location is not supported by this browser. Enter your address instead.'); return } setLocating(true); navigator.geolocation.getCurrentPosition(p => { if (!alive.current) return; setValues(v => ({ ...v, latitude: String(p.coords.latitude), longitude: String(p.coords.longitude) })); setLocating(false) }, () => { if (!alive.current) return; setLocating(false); mutation.setError('Unable to get your location. You can still enter your address manually.') }, { timeout: 10000 }) }}><Icon name="pin" />Use current location</Button>{values.latitude && <Notice>Coordinates captured: {values.latitude}, {values.longitude}. Use this only when you are at your gym.</Notice>}</>}
      {step === 2 && <><Input label="Day pass price (INR)" type="number" min="0" step="0.01" value={values.gym_price_per_person} required onChange={e => field('gym_price_per_person', e.target.value)} /><label className="ow-check"><input type="checkbox" checked={values.has_classes} onChange={e => field('has_classes', e.target.checked)} />This gym offers classes</label><Notice>Membership and class prices are managed separately. This price applies to gym access per person.</Notice></>}
      {step === 3 && gym && <Photos gym={gym} onSaved={() => void api.fetchGymDetailsOwner(gym.id).then(setGym).catch(e => mutation.setError(e instanceof Error ? e.message : 'Unable to reload photos.'))} />}
      {step === 4 && (facilityResource.loading ? <Skeleton /> : facilityResource.error ? <ErrorState message={facilityResource.error} retry={facilityResource.retry} /> : <div className="ow-facilities">{facilityResource.data?.length ? facilityResource.data.map(f => <label key={f.id} className={`ow-facility ${facilities.includes(f.id) ? 'is-selected' : ''}`}><input type="checkbox" checked={facilities.includes(f.id)} onChange={e => setFacilities(items => e.target.checked ? [...items, f.id] : items.filter(id => id !== f.id))} />{f.name}</label>) : <EmptyState title="No facilities available" description="The facility catalog is currently empty." />}</div>)}
      {step === 5 && <><Button variant="secondary" onClick={() => setHours(h => h.map((item, i) => ({ ...h[0], day_of_week: i })))}>Copy Monday to all days</Button><div className="ow-hours-editor">{hours.map((h, i) => <div key={i}><strong>{days[i]}</strong><label className="ow-check"><input type="checkbox" checked={h.is_closed} onChange={e => setHours(all => all.map((item, n) => n === i ? { ...item, is_closed: e.target.checked } : item))} />Closed</label>{!h.is_closed && <><Input label="Opens" type="time" required value={h.open_time?.slice(0, 5) || ''} onChange={e => setHours(all => all.map((item, n) => n === i ? { ...item, open_time: e.target.value } : item))} /><Input label="Closes" type="time" required value={h.close_time?.slice(0, 5) || ''} onChange={e => setHours(all => all.map((item, n) => n === i ? { ...item, close_time: e.target.value } : item))} /></>}</div>)}</div><Notice>Closing time must be after opening time. Overnight hours are not supported by the current backend.</Notice></>}
      {step === 6 && gym && <div className="ow-stack"><h3>{gym.name}</h3><p>{gym.description || 'No description added.'}</p><p>{[gym.address_line_1, gym.city, gym.state, gym.postal_code].filter(Boolean).join(', ') || 'Address not added.'}</p><p className="ow-price">{money(gym.gym_price_per_person || '0')}<small> / day pass</small></p><div className="ow-facilities">{gym.facilities.map(f => <span key={f.id} className="ow-facility is-selected"><Icon name="check" />{f.name}</span>)}</div><div className="ow-photo-grid">{gym.images.map(i => <Image key={i.id} src={`/uploads/${i.file_path}`} alt={gym.name} />)}</div><div className="ow-hours">{gym.operating_hours.map(h => <div key={h.day_of_week}><strong>{days[h.day_of_week]}</strong><span>{h.is_closed ? 'Closed' : `${h.open_time?.slice(0, 5)} – ${h.close_time?.slice(0, 5)}`}</span></div>)}</div><Notice>Review the information above. Missing sections can be completed by going back. Submission rules are validated by FitiGo.</Notice></div>}
      {mutation.error && <Notice tone="error">{mutation.error}</Notice>}<div className="ow-wizard-actions"><Button variant="secondary" disabled={step === 0 || mutation.pending} onClick={() => setStep(s => s - 1)}>Back</Button><Button variant="text" disabled={mutation.pending} onClick={() => { if (!formRef.current?.reportValidity()) return; void mutation.run(async () => { await saveStep(); toast('Gym saved.'); }) }}>{gym?.status && gym.status !== 'DRAFT' ? 'Save changes' : 'Save draft'}</Button>{step < 6 ? <Button type="submit" loading={mutation.pending} disabled={step === 4 && (facilityResource.loading || !!facilityResource.error)}>Save & continue<Icon name="arrow" size={16} /></Button> : gym?.status === 'DRAFT' ? <Button disabled={mutation.pending} onClick={() => setConfirm(true)}>Submit for approval</Button> : gym && <Link to={`/owner/gyms/${gym.id}`} className="fg-button fg-button--primary">Done</Link>}</div>
    </form></div></Card></div>{confirm && gym && <ConfirmDialog title="Submit gym for approval?" label="Submit for approval" pending={mutation.pending} error={mutation.error} onClose={() => setConfirm(false)} onConfirm={() => void mutation.run(async () => { await api.submitGymForApproval(gym.id); refreshGyms(); toast('Gym submitted for approval.'); navigate(`/owner/gyms/${gym.id}`) })}>Your saved gym details will be sent for review.</ConfirmDialog>}</div>
}