import { useState } from 'react'
import * as api from '../screens/GymOwner/api'
import { useMutation, useResource } from '../hooks/useResource'
import { useOwner } from './context'
import { Breadcrumbs, Button, Card, ConfirmDialog, EmptyState, ErrorState, Field, Input, Link, Notice, PageHeader, Skeleton, StatusBadge } from './UI'
import { localDate, money } from '../services/client'
import { navigate } from '../router'
import Icon from '../components/common/Icon'
import type { OwnerRoute } from './routes'

export default function Operations({ route }: { route: OwnerRoute }) {
  if (route.page.startsWith('staff')) return <Staff route={route} />
  return <Catalog route={route} />
}
function Catalog({ route }: { route: OwnerRoute }) {
  const { gymId, gym, toast } = useOwner(); const plans = route.page === 'memberships'
  const mutation = useMutation(); const [confirm, setConfirm] = useState<api.OwnerSlot | api.OwnerMembershipPlan | null>(null)
  const resource = useResource<(api.OwnerSlot | api.OwnerMembershipPlan)[]>(() => !gymId ? Promise.resolve([]) : plans ? api.listOwnerMembershipPlans(gymId) : api.listOwnerSlots(gymId), `catalog:${plans}:${gymId}`)
  const [date, setDate] = useState(localDate())
  const availability = useResource(() => gymId && route.page === 'slots' && gym?.status === 'APPROVED' && gym.is_active ? api.listPublicSlotAvailability(gymId, date) : Promise.resolve([]), `availability:${gymId}:${route.page}:${date}`)
  if (!gymId) return <EmptyState title="Select a gym" action={<Link to="/owner/gyms">View gyms</Link>} />
  const base = `/owner/gyms/${gymId}/${plans ? 'memberships' : 'classes'}`
  if (resource.loading) return <Skeleton />
  if (resource.error) return <ErrorState message={resource.error} retry={resource.retry} />
  const selected = resource.data?.find(item => item.id === route.id)
  if (route.id && !selected) return <EmptyState title={plans ? 'Plan not found' : 'Class not found'} action={<Link to={base}>Back to list</Link>} />
  if (route.mode) return <CatalogForm plans={plans} gymId={gymId} initial={selected} base={base} />
  const items = selected ? [selected] : resource.data || []
  return <div className="ow-stack"><Breadcrumbs items={[{ label: 'My gyms', to: '/owner/gyms' }, { label: gym?.name || 'Gym', to: `/owner/gyms/${gymId}` }, { label: plans ? 'Membership plans' : 'Classes & slots' }]} /><PageHeader title={selected ? selected.name : plans ? 'Membership plans' : route.page === 'slots' ? 'Slot availability' : 'Classes & slots'} description={`${gym?.name} · ${plans ? 'Memberships built around your community.' : 'Keep every session running smoothly.'}`} action={<Link to={`${base}/create`} className="fg-button fg-button--primary"><Icon name="plus" />{plans ? 'Create plan' : 'Create class'}</Link>} />
    {!plans && <><div className="ow-actions"><Link className="fg-button fg-button--secondary" to={base}>Class configuration</Link><Link className="fg-button fg-button--secondary" to={`/owner/gyms/${gymId}/slots`}>Slot availability</Link>{route.page === 'slots' && <Input label="Availability date" type="date" value={date} onChange={e => e.target.value && setDate(e.target.value)} />}</div><Notice>These controls manage owner slot records. The backend does not synchronize edits or deactivation to separately generated customer class sessions. Slot availability below is not class-session availability.</Notice></>}
    {route.page === 'slots' && (gym?.status !== 'APPROVED' || !gym.is_active ? <Notice>Customer-facing availability is returned only for approved, active gyms.</Notice> : availability.loading ? <Skeleton cards={1} /> : availability.error ? <ErrorState message={availability.error} retry={availability.retry} /> : <Notice>Availability below comes directly from the customer slot API for {date}. It is not calculated from booking counts.</Notice>)}
    {!items.length ? <Card><EmptyState title={plans ? 'No membership plans yet' : 'No classes configured'} description={plans ? 'Create your first membership offering.' : 'Add a class with its time, capacity and price.'} action={<Link className="fg-button fg-button--primary" to={`${base}/create`}>{plans ? 'Create plan' : 'Create class'}</Link>} /></Card> : <div className="ow-card-grid">{items.map(item => { const plan = 'duration_days' in item ? item : null; const slot = 'capacity' in item ? item : null; const av = availability.data?.find(a => a.id === item.id)?.availability; return <Card key={item.id}><div className="ow-stack"><div className="ow-card-heading"><span className="ow-icon-tile"><Icon name={plans ? 'ticket' : 'clock'} /></span><StatusBadge status={item.is_active ? 'ACTIVE' : 'INACTIVE'} /></div><h2>{item.name}</h2>{plan ? <><p className="ow-price">{money(plan.price, plan.currency)}<small> / {plan.duration_days} days</small></p><p className="ow-muted">{plan.description || 'No description added.'}</p></> : slot && <><p>{slot.start_time.slice(0, 5)} – {slot.end_time.slice(0, 5)}</p><dl className="ow-details"><div><dt>Capacity</dt><dd>{slot.capacity} people</dd></div><div><dt>Price</dt><dd>{money(slot.price)}</dd></div>{route.page === 'slots' && av && <><div><dt>Booked</dt><dd>{av.booked_count}</dd></div><div><dt>Available</dt><dd>{av.remaining_capacity}</dd></div></>}</dl>{route.page === 'slots' && !av && <p className="ow-caption">No customer availability returned for this slot/date.</p>}{av && <StatusBadge status={av.status} />}</>}<div className="ow-actions"><Link className="fg-button fg-button--secondary" to={`${base}/${item.id}/edit`}>Edit {plans ? 'plan' : 'class'}</Link><Button variant={item.is_active ? 'danger' : 'text'} onClick={() => setConfirm(item)}>{item.is_active ? 'Deactivate' : 'Activate'}</Button></div></div></Card> })}</div>}
    {confirm && <ConfirmDialog title={`${confirm.is_active ? 'Deactivate' : 'Activate'} ${plans ? 'plan' : 'class'}?`} label="Confirm change" destructive={confirm.is_active} pending={mutation.pending} error={mutation.error} onClose={() => setConfirm(null)} onConfirm={() => void mutation.run(async () => { if (plans) { if (confirm.is_active) await api.deactivateOwnerMembershipPlan(confirm.id); else await api.activateOwnerMembershipPlan(confirm.id) } else { if (confirm.is_active) await api.deactivateOwnerSlot(confirm.id); else await api.updateOwnerSlot(confirm.id, { is_active: true }) } setConfirm(null); resource.retry(); availability.retry(); toast('Configuration updated.') })}>Update the availability of “{confirm.name}”. Existing booking and membership rules remain controlled by FitiGo.</ConfirmDialog>}
  </div>
}
function CatalogForm({ plans, gymId, initial, base }: { plans: boolean; gymId: number; initial?: api.OwnerMembershipPlan | api.OwnerSlot; base: string }) {
  const mutation = useMutation(); const { toast } = useOwner(); const [schedule, setSchedule] = useState('date'); const [repeat, setRepeat] = useState<number[]>([])
  const plan = initial && 'duration_days' in initial ? initial : undefined; const slot = initial && 'capacity' in initial ? initial : undefined
  const [pauseAllowed, setPauseAllowed] = useState(plan?.pause_policy?.allowed ?? false)
  return <div className="ow-stack ow-form-page"><Breadcrumbs items={[{ label: plans ? 'Membership plans' : 'Classes', to: base }, { label: initial ? 'Edit' : 'Create' }]} /><PageHeader title={`${initial ? 'Edit' : 'Create'} ${plans ? 'membership plan' : 'class'}`} description={plans ? 'A clear offering makes joining easier.' : 'Set up the essentials for a great session.'} /><Card><form className="ow-stack" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); void mutation.run(async () => {
    if (plans) { const payload = { name: String(form.get('name')).trim(), description: String(form.get('description')).trim() || null, duration_days: Number(form.get('duration')), price: String(form.get('price')), currency: String(form.get('currency')).trim().toUpperCase(), pause_policy: { allowed: pauseAllowed, max_pause_days: pauseAllowed ? Number(form.get('max_pause_days')) : 0 } }; if (initial) await api.updateOwnerMembershipPlan(initial.id, payload); else await api.createOwnerMembershipPlan(gymId, payload) }
    else { const payload = { name: String(form.get('name')).trim(), start_time: String(form.get('start')), end_time: String(form.get('end')), capacity: Number(form.get('capacity')), price: String(form.get('price')) }; if (initial) await api.updateOwnerSlot(initial.id, payload); else { if (schedule === 'repeat' && !repeat.length) throw new Error('Choose at least one repeat day.'); await api.createOwnerSlot(gymId, { ...payload, specific_date: schedule === 'date' ? String(form.get('date')) : null, repeat_days: schedule === 'repeat' ? repeat : [] }) } }
    toast(plans ? 'Membership plan saved.' : 'Class saved.'); navigate(base)
  }) }}><Input label={plans ? 'Plan name' : 'Class name'} name="name" required minLength={2} maxLength={plans ? 120 : 100} defaultValue={initial?.name} />
    {plans && <fieldset className="ow-stack"><legend>Pause policy</legend><label className="ow-check"><input name="pause_allowed" type="checkbox" checked={pauseAllowed} onChange={e => setPauseAllowed(e.target.checked)} />Allow Pause</label><Input label="Maximum pause days" name="max_pause_days" type="number" min={1} step={1} required={pauseAllowed} disabled={!pauseAllowed} defaultValue={plan?.pause_policy?.max_pause_days || ''} /><small>Applies to future requests for this plan. Accepted pauses remain honored.</small></fieldset>}
    {plans ? <><Field label="Description / benefits"><textarea name="description" rows={4} maxLength={2000} defaultValue={plan?.description || ''} /></Field><div className="ow-form-grid"><Input label="Duration (days)" name="duration" type="number" required min={1} max={3660} defaultValue={plan?.duration_days} /><Input label="Currency" name="currency" required maxLength={10} defaultValue={plan?.currency || 'INR'} /></div></> : <><div className="ow-form-grid"><Input label="Start time" type="time" name="start" required defaultValue={slot?.start_time.slice(0, 5)} /><Input label="End time" type="time" name="end" required defaultValue={slot?.end_time.slice(0, 5)} /></div><Input label="Capacity" name="capacity" type="number" required min={1} max={500} defaultValue={slot?.capacity} />{initial ? <Notice>This updates the owner slot only. Existing customer class sessions are not synchronized by the backend. Schedule, trainer and description are not returned.</Notice> : <><Field label="Schedule"><select value={schedule} onChange={e => setSchedule(e.target.value)}><option value="date">Specific date</option><option value="repeat">Weekly (next 30 days)</option></select></Field>{schedule === 'date' ? <Input label="Date" name="date" type="date" required /> : <fieldset><legend>Repeat on</legend><div className="ow-facilities">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day, i) => <label className="ow-check" key={day}><input type="checkbox" checked={repeat.includes(i)} onChange={e => setRepeat(list => e.target.checked ? [...list, i] : list.filter(v => v !== i))} />{day}</label>)}</div></fieldset>}</>}</>}
    <Input label={plans ? 'Price' : 'Price (INR)'} type="number" step="0.01" min="0" name="price" required defaultValue={initial?.price} />{mutation.error && <Notice tone="error">{mutation.error}</Notice>}<div className="ow-actions"><Link to={base} className="fg-button fg-button--secondary">Cancel</Link><Button type="submit" loading={mutation.pending}>Save {plans ? 'plan' : 'class'}</Button></div>
  </form></Card></div>
}
function Staff({ route }: { route: OwnerRoute }) {
  const { gymId, gym, toast } = useOwner(); const resource = useResource(() => gymId ? api.listStaff(gymId) : Promise.resolve([]), `staff:${gymId}`); const mutation = useMutation(); const [remove, setRemove] = useState<api.StaffAssignment | null>(null)
  if (!gymId) return <EmptyState title="Select a gym" action={<Link to="/owner/gyms">View gyms</Link>} />
  if (route.page === 'staffForm') return <div className="ow-form-page ow-stack"><Breadcrumbs items={[{ label: 'Staff', to: '/owner/staff' }, { label: 'Add staff' }]} /><PageHeader title="Add to your team" description={`Create a staff assignment for ${gym?.name}.`} /><Card><form className="ow-stack" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); void mutation.run(async () => { await api.inviteStaff(gymId, { email: String(form.get('email')).trim().toLowerCase(), first_name: String(form.get('first_name')).trim() || null, last_name: String(form.get('last_name')).trim() || null }); toast('Staff assignment created. Email delivery is not provided by this endpoint.'); navigate('/owner/staff') }) }}><Input label="Email address" name="email" type="email" required /><div className="ow-form-grid"><Input label="First name (optional)" name="first_name" maxLength={100} /><Input label="Last name (optional)" name="last_name" maxLength={100} /></div><Notice>The current backend creates a GYM_STAFF assignment with check-in and attendance access. Custom manager roles and emailed invitations are not available.</Notice>{mutation.error && <Notice tone="error">{mutation.error}</Notice>}<div className="ow-actions"><Link to="/owner/staff" className="fg-button fg-button--secondary">Cancel</Link><Button type="submit" loading={mutation.pending}>Add staff member</Button></div></form></Card></div>
  if (resource.loading) return <Skeleton />
  if (resource.error) return <ErrorState message={resource.error} retry={resource.retry} />
  const selected = route.id ? resource.data?.find(s => s.user_id === route.id) : undefined
  if (route.id && !selected) return <EmptyState title="Staff assignment not found" action={<Link to="/owner/staff">Back to staff</Link>} />
  const items = selected ? [selected] : resource.data || []
  return <div className="ow-stack"><PageHeader title="Your team" description={`Staff assignments · ${gym?.name}`} action={<Link to="/owner/staff/invite" className="fg-button fg-button--primary"><Icon name="plus" />Add staff</Link>} /><Notice>Only staff IDs and assigned roles are returned by the API. Names, invitation delivery and last-active times are not available.</Notice>{!items.length ? <Card><EmptyState title="No staff members" description="Add your team to help with daily operations." action={<Link to="/owner/staff/invite" className="fg-button fg-button--primary">Add staff member</Link>} /></Card> : <div className="ow-card-grid">{items.map(s => <Card key={s.id}><div className="ow-stack"><span className="ow-avatar"><Icon name="user" /></span><h2>Staff #{s.user_id}</h2><StatusBadge status={s.role} /><p className="ow-muted">Assignment #{s.id}</p>{selected && <Notice>Assigned staff can validate QR access and record booking attendance. Server authorization is required for every action.</Notice>}<div className="ow-actions"><Link className="fg-button fg-button--secondary" to={`/owner/staff/${s.user_id}`}>View permissions</Link><Button variant="danger" onClick={() => setRemove(s)}>Remove access</Button></div></div></Card>)}</div>}{remove && <ConfirmDialog title="Remove staff access?" label="Remove access" destructive pending={mutation.pending} error={mutation.error} onClose={() => setRemove(null)} onConfirm={() => void mutation.run(async () => { await api.removeStaff(gymId, remove.user_id); setRemove(null); resource.retry(); toast('Staff access removed.'); if (route.id) navigate('/owner/staff') })}>Staff #{remove.user_id} will no longer be assigned to this gym.</ConfirmDialog>}</div>
}