ROLE_CUSTOMER = "CUSTOMER"
ROLE_GYM_OWNER = "GYM_OWNER"
ROLE_GYM_STAFF = "GYM_STAFF"
ROLE_ADMIN = "ADMIN"
ROLE_SUPER_ADMIN = "SUPER_ADMIN"

ALL_ROLES = {
    ROLE_CUSTOMER,
    ROLE_GYM_OWNER,
    ROLE_GYM_STAFF,
    ROLE_ADMIN,
    ROLE_SUPER_ADMIN,
}
